project:
  type: website
  output-dir: docs

website:
  title: "NMEP Data & Analytics Documentation"
  navbar:
    left:
      - text: Dashboard Guide
        href: index.qmd
      - text: Monthly bulletin guide
        href: bulletin/NMEP monthly bulletin workflow.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    code-copy: true
    code-fold: true