project:
  type: website
  output-dir: docs

website:
  title: "NMEP Data & Analytics Documentation Portal"

  navbar:
    left:
      - text: Home
        href: index.qmd
     # - text: Dashboard Guide
     #   href: dashboard/index.qmd
     # - text: Bulletin Workflow
      #  href: bulletin/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    code-copy: true
    code-fold: true